// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// This `datasource.url` is used ONLY by the Prisma CLI
// (migrate/introspect/validate), never by the deployed app: the Next.js
// app builds its own `PrismaPg` driver adapter directly from
// `DATABASE_URL` at runtime (see apps/operator/src/lib/prisma/client.ts),
// entirely independent of this config file. The pooled DATABASE_URL
// (Supabase PgBouncer, transaction mode, port 6543) works fine for that
// runtime adapter but the CLI's schema engine hung indefinitely against it
// for migrate/introspect (confirmed: `migrate status`/`migrate dev`/
// `db push` all hung; the generated Query Engine client succeeded against
// the exact same URL). Prisma 7 removed schema-level `url`/`directUrl`
// support entirely (see the `prisma validate` error pointing at
// https://pris.ly/d/config-datasource) — the CLI-only connection now
// belongs here instead. DIRECT_URL is a direct (non-pooled) connection to
// the same database; DATABASE_URL itself is deliberately left untouched.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
