import type { CropFinding } from "@/lib/findings/types";
import type { SensorAlertRecord } from "@/lib/sensor-analytics/types";
import type { AgriculturalWeatherAnalysis, WeatherRiskFactor } from "@/lib/weather/types";

/**
 * The ENTIRE Farm State classification rule, exactly as approved in the
 * MVP-UI.2-A audit and the governing prompt. This module
 * is deliberately plain TypeScript (no "use client", no React) so the
 * Farmer Dashboard's Server Component can call it directly during render,
 * mirroring how that page already derives `activeMissionCount` etc. inline
 * — this is a classification step over already-fetched data, not a new
 * fetch, store, or service.
 *
 * DATA HONESTY (the mandatory rule): every field read
 * below already exists on `CropFinding`/`SensorAlertRecord`/
 * `AgriculturalWeatherAnalysis` — nothing here invents a weight, a score,
 * or a percentage. The output is a LABEL (`FarmStateLevel`) plus a short
 * list of the concrete real facts that produced it, never a number.
 */

export type FarmStateLevel = "healthy" | "attention" | "critical";

/**
 * A single concrete, real fact behind the current Farm State — structured
 * (not a pre-formatted string) so the presentational layer can translate
 * the label text while a `"weather"` reason's own `text` (real English
 * sentence generated by `agricultural-analysis.ts`) rides through
 * untranslated, exactly like this app's existing Alert-message convention.
 */
export type FarmStateReason =
  | { kind: "critical-findings"; count: number }
  | { kind: "critical-alerts"; count: number }
  | { kind: "medium-findings"; count: number }
  | { kind: "warning-alerts"; count: number }
  | { kind: "weather"; level: Extract<WeatherRiskFactor["level"], "high-risk" | "caution">; text: string };

export interface FarmStateResult {
  level: FarmStateLevel;
  /** Capped at `MAX_REASONS`, ordered most-severe-first — a restrained hero shows a few concrete facts, not an exhaustive report. */
  reasons: FarmStateReason[];
}

const MAX_REASONS = 3;

export interface FarmStateInput {
  /** Already filtered to unresolved (`status !== "resolved"`) — the SAME array the Dashboard page already computes for its own "Open Crop Issues" count; only `severity` is read. */
  unresolvedFindings: Pick<CropFinding, "severity">[];
  /** Already filtered to unresolved (`resolvedAt === null`) — the SAME array the Dashboard page already computes for its own "Unresolved Alerts" count; only `severity` is read. */
  unresolvedAlerts: Pick<SensorAlertRecord, "severity">[];
  /** `null` whenever the farm has no configured location or the weather fetch failed — the SAME nullable snapshot the Dashboard page already handles for its Weather card. */
  weatherAnalysis: AgriculturalWeatherAnalysis | null;
}

/**
 * The 6 weather factors this change treats as genuine attention signals.
 * `irrigationConsideration` is deliberately excluded: its own doc comment
 * (`weather/types.ts`) states it is worded as a "consideration", never a
 * directive/risk — folding it into an "attention" framing would overstate
 * what that field is actually meant to communicate.
 */
function weatherRiskFactors(analysis: AgriculturalWeatherAnalysis): WeatherRiskFactor[] {
  return [analysis.droneOperations, analysis.robotOperations, analysis.fieldConditions, analysis.rainRisk, analysis.windRisk, analysis.heatRisk];
}

/**
 * CRITICAL: any unresolved critical alert OR any unresolved high/critical
 * finding.
 * NEEDS ATTENTION (only checked when not already CRITICAL): any unresolved
 * warning alert OR any unresolved medium finding OR any weather factor at
 * caution/high-risk.
 * HEALTHY: none of the above.
 *
 * This is the exact rule this change's governing prompt specifies — no
 * additional weighting, no combination logic beyond these plain boolean
 * checks.
 */
export function deriveFarmState(input: FarmStateInput): FarmStateResult {
  const criticalFindingsCount = input.unresolvedFindings.filter((finding) => finding.severity === "high" || finding.severity === "critical").length;
  const mediumFindingsCount = input.unresolvedFindings.filter((finding) => finding.severity === "medium").length;
  const criticalAlertsCount = input.unresolvedAlerts.filter((alert) => alert.severity === "critical").length;
  const warningAlertsCount = input.unresolvedAlerts.filter((alert) => alert.severity === "warning").length;

  const factors = input.weatherAnalysis ? weatherRiskFactors(input.weatherAnalysis) : [];
  const highRiskFactor = factors.find((factor) => factor.level === "high-risk") ?? null;
  const cautionFactor = factors.find((factor) => factor.level === "caution") ?? null;

  const isCritical = criticalAlertsCount > 0 || criticalFindingsCount > 0;
  const isAttention = !isCritical && (warningAlertsCount > 0 || mediumFindingsCount > 0 || highRiskFactor !== null || cautionFactor !== null);
  const level: FarmStateLevel = isCritical ? "critical" : isAttention ? "attention" : "healthy";

  // Priority order: the two real database-backed signals first (findings,
  // then alerts), then a single weather-derived fact (the worst one
  // available — never both a high-risk AND a caution line for the same
  // hero, to keep it restrained), then the two lower-severity signals.
  const reasons: FarmStateReason[] = [];
  if (criticalFindingsCount > 0) reasons.push({ kind: "critical-findings", count: criticalFindingsCount });
  if (criticalAlertsCount > 0) reasons.push({ kind: "critical-alerts", count: criticalAlertsCount });
  const weatherFactor = highRiskFactor ?? cautionFactor;
  if (weatherFactor) reasons.push({ kind: "weather", level: weatherFactor.level as "high-risk" | "caution", text: weatherFactor.reason });
  if (mediumFindingsCount > 0) reasons.push({ kind: "medium-findings", count: mediumFindingsCount });
  if (warningAlertsCount > 0) reasons.push({ kind: "warning-alerts", count: warningAlertsCount });

  return { level, reasons: reasons.slice(0, MAX_REASONS) };
}
