"use client";

import { AlertOctagon, AlertTriangle, CheckCircle2 } from "lucide-react";

import { Card, CardContent, cn, Typography } from "@agrinexus/ui";

import type { FarmStateReason, FarmStateResult } from "@/lib/farmer/farm-state";
import { useFarmerTranslation } from "@/lib/farmer/i18n/use-farmer-translation";
import type { FarmerTranslation, FarmerTranslationKey } from "@/lib/farmer/i18n/use-farmer-translation";

/**
 * The new dominant visual on the Farmer Dashboard. A thin, "use client"
 * presentational wrapper around the real, already-classified
 * `FarmStateResult` (computed server-side by `deriveFarmState`, see that
 * module's own doc comment) — mirrors the exact `FarmerKpiCard`/`FarmerT`
 * pattern this file's own page already uses elsewhere: the Server
 * Component computes real data, a small client leaf resolves the
 * Farmer's chosen display language for the label text around it.
 *
 * Uses only the EXISTING Card system (`variant="elevated"`, the same
 * variant MVP-UI.1-B already reserves for a page's most important
 * surface) and the EXISTING semantic status tokens (success/warning/
 * critical, muted variants) — no new design system, no new colors, no
 * gradient/glow decoration, per this change's explicit visual-design
 * rule.
 */

const LEVEL_LABEL_KEYS: Record<FarmStateResult["level"], FarmerTranslationKey> = {
  healthy: "dashboard.farmStateHealthy",
  attention: "dashboard.farmStateAttention",
  critical: "dashboard.farmStateCritical",
};

const REASON_LABEL_KEYS: Partial<Record<FarmStateReason["kind"], FarmerTranslationKey>> = {
  "critical-findings": "dashboard.reasonCriticalFindings",
  "critical-alerts": "dashboard.reasonCriticalAlerts",
  "medium-findings": "dashboard.reasonMediumFindings",
  "warning-alerts": "dashboard.reasonWarningAlerts",
};

function ReasonLine({ reason, t }: { reason: FarmStateReason; t: FarmerTranslation["t"] }) {
  if (reason.kind === "weather") {
    // Real, English-only sentence generated by `agricultural-analysis.ts`
    // (e.g. "Wind 34 km/h exceeds typical drone-safe limits.") — never
    // translated, the exact same rule this app already applies to Alert
    // `message`/mission/vehicle names. `<bdi>` isolates it under Urdu RTL,
    // matching every other farm-data string on this page.
    return <bdi>{reason.text}</bdi>;
  }
  const key = REASON_LABEL_KEYS[reason.kind];
  if (!key) return null;
  return (
    <bdi>
      {reason.count} {t(key)}
    </bdi>
  );
}

const LEVEL_STYLES: Record<FarmStateResult["level"], { icon: typeof CheckCircle2; text: string; badge: string }> = {
  healthy: { icon: CheckCircle2, text: "text-success", badge: "bg-success-muted" },
  attention: { icon: AlertTriangle, text: "text-warning", badge: "bg-warning-muted" },
  critical: { icon: AlertOctagon, text: "text-critical", badge: "bg-critical-muted" },
};

export function FarmStateHero({ level, reasons }: FarmStateResult) {
  const { t } = useFarmerTranslation();
  const { icon: Icon, text, badge } = LEVEL_STYLES[level];

  return (
    <Card variant="elevated">
      <CardContent className="flex items-start gap-4 py-5">
        <span className={cn("flex size-12 shrink-0 items-center justify-center rounded-2xl", badge)}>
          <Icon className={cn("size-6", text)} aria-hidden />
        </span>
        <div className="flex min-w-0 flex-col gap-1">
          <Typography variant="caption">{t("dashboard.farmState")}</Typography>
          {/* `as="h2"` — the Dashboard's own page title (`as="h1"`, see page.tsx) stays the document's single h1; this is the first, and now visually dominant, section heading beneath it. Visual size intentionally exceeds the page title's own (now-demoted, see page.tsx) size — a hero stat outranking a page's own small title is normal and does not require matching heading levels to visual size, only correct nesting order. */}
          <Typography variant="display" as="h2" className={text}>
            {t(LEVEL_LABEL_KEYS[level])}
          </Typography>
          {/*
            A SINGLE `Typography`/`<p>` for every reason, each one an inline
            `<span>` preceded by a plain text " · " separator (not its own
            flex row) — lets the browser's normal inline line-breaking wrap
            naturally between reasons on narrow viewports, rather than ever
            stranding a separator alone on its own line (found and fixed
            during this milestone's own live-screenshot verification).
          */}
          <Typography variant="small" className="text-foreground-muted">
            {level === "healthy" ? (
              <bdi>{t("dashboard.farmStateHealthyReason")}</bdi>
            ) : (
              reasons.map((reason, index) => (
                <span key={index}>
                  {index > 0 ? " · " : ""}
                  <ReasonLine reason={reason} t={t} />
                </span>
              ))
            )}
          </Typography>
        </div>
      </CardContent>
    </Card>
  );
}
